version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 4040:4040
    container_name: playflock-server
    networks:
      - PlayFlock-tz
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: playflock-client
    networks:
      - PlayFlock-tz
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    stdin_open: true
    tty: true

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - PlayFlock-tz
    volumes:
      - mongo-data:/data/db

networks:
  PlayFlock-tz:
    driver: bridge

volumes:
  mongo-data:
    driver: local
