# version: "3"

# services:
#   mongo_db:
#     container_name: db_container
#     image: mongo:latest
#     restart: always
#     volumes:
#       - mongo_db:/data/db

#   api:
#     build: .
#     ports:
#       - 3000:5000
#     environment:
#       PORT: 5000
#       MONGO_SERVER: mongodb+srv://Ramzan:code@cluster0.ikkq5.mongodb.net/PlayFlock?retryWrites=true&w=majority
#     depends_on:
#       - mongo_db

# volumes:
#   mongo_db: {}

version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: PlayFlock-client
    networks:
      - PlayFlock-tz
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    container_name: PlayFlock-server
    networks:
      - PlayFlock-tz
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - PlayFlock-tz
    volumes:
      - mongo-data:/data/db

networks:
  PlayFlock-tz:
    driver: bridge

volumes:
  mongo-data:
    driver: local
