version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 4000:5000
    environment:
      PORT: 5000
      MONGO_SERVER: mongodb+srv://Ramzan:code@cluster0.ikkq5.mongodb.net/PlayFlock?retryWrites=true&w=majority
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}